import './color-studio.css'
let panel=null,returnFocus=null,revision=0,timer=0
const state={source:null,name:'',count:5,palette:[],edited:false}
const hex=rgb=>'#'+rgb.map(x=>Math.round(x).toString(16).padStart(2,'0')).join('').toUpperCase()
const rgb=value=>value.slice(1).match(/../g).map(x=>parseInt(x,16))
function luminance(color){return color.map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4}).reduce((sum,x,i)=>sum+x*[.2126,.7152,.0722][i],0)}
function contrast(color){const l=luminance(color),black=(l+.05)/.05,white=1.05/(l+.05);return {text:black>=white?'#000000':'#FFFFFF',ratio:Math.max(black,white)}}
export function openColorStudio(onReturn=null){
 returnFocus=onReturn;document.getElementById('pixora-universe-home')?.setAttribute('inert','');document.body.style.overflow='hidden'
 if(panel){panel.hidden=false;panel.querySelector('.cs-upload').focus();return}
 panel=document.createElement('section');panel.id='color-studio';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','色彩分析工作台')
 panel.innerHTML=`<header class="cs-header"><button class="cs-back">← 回到行星選單</button><div class="cs-brand"><i></i><b>PIXORA<br>COLOR INDEX</b></div><span>VENUS / LOCAL MODE</span><button class="cs-reset">重新開始</button></header><div class="cs-shell"><aside class="cs-intro"><small>WORKBENCH / VENUS</small><h1>讀懂圖片的<br><em>色彩。</em></h1><p>從一張圖片開始，建立一份可以帶走的色彩索引。</p><ol><li>放入圖片<small>ANALYZE IMAGE</small></li><li>查看色票<small>READ PALETTE</small></li><li>建立輸出<small>BUILD OUTPUT</small></li></ol><p class="cs-note">圖片不會上傳。<br>色票比例為取樣像素的估計值。透明區域不參與分析。</p></aside><main class="cs-main"><div class="cs-toolbar"><span>IMAGE → COLOR / LOCAL</span><button class="cs-upload">選擇圖片</button><input class="cs-file" type="file" accept="image/png,image/jpeg,image/webp,image/avif" hidden><button class="cs-demo">試用範例</button></div><section class="cs-drop" tabindex="0" role="button" aria-label="上傳或拖放圖片"><div class="cs-empty"><b>放入圖片，讀懂色彩。</b><p>拖放或點擊上傳 JPG / PNG / WEBP / AVIF<br>支援 20MB 以下的圖片</p><span>ADD IMAGE ↗</span></div><img class="cs-image" alt="待分析圖片" hidden></section><div class="cs-meta"><span class="cs-source">尚未加入圖片</span><label for="cs-count">色票數量</label><select id="cs-count">${[3,5,8,10].map(n=>`<option value="${n}" ${n===5?'selected':''}>${n} 色</option>`).join('')}</select></div><section class="cs-palette-section"><div class="cs-heading"><div><small>EXTRACTED COLORS</small><h2>你的色彩索引</h2></div><button class="cs-copy-all">複製全部色碼</button></div><p class="cs-status" role="status">加入圖片後開始分析。</p><div class="cs-palette"></div></section><section class="cs-output"><small>BUILD OUTPUT</small><h2>把色彩帶走。</h2><p>下載色票圖片或可直接使用的設計資料。</p><div><button data-export="png">下載色票 PNG</button><button data-export="css">匯出 CSS</button><button data-export="json">匯出 JSON</button></div><p class="cs-note">使用 RGB 色彩。此工具不提供 Pantone 認證配色或印刷 CMYK 轉換。</p></section></main></div><div class="cs-toast" role="status"></div>`
 document.body.append(panel)
 panel.querySelector('.cs-back').onclick=close
 const input=panel.querySelector('.cs-file'),drop=panel.querySelector('.cs-drop');panel.querySelector('.cs-upload').onclick=()=>input.click();drop.onclick=()=>input.click();drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}}
 input.onchange=e=>{accept(e.target.files?.[0]);input.value=''}
 drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');accept(e.dataTransfer.files[0])}
 panel.querySelector('#cs-count').onchange=e=>{state.count=Number(e.target.value);if(state.source)analyze()}
 panel.querySelector('.cs-demo').onclick=demo
 panel.querySelector('.cs-reset').onclick=()=>{revision++;state.source=null;state.name='';state.palette=[];state.edited=false;panel.querySelector('.cs-image').hidden=true;panel.querySelector('.cs-image').removeAttribute('src');panel.querySelector('.cs-empty').hidden=false;panel.querySelector('.cs-source').textContent='尚未加入圖片';panel.querySelector('.cs-status').textContent='加入圖片後開始分析。';render()}
 panel.querySelector('.cs-copy-all').onclick=()=>copy(state.palette.map(x=>x.hex).join(', '))
 panel.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportPalette(b.dataset.export))
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)close()});render();panel.querySelector('.cs-upload').focus()
}
function close(){panel.hidden=true;document.body.style.overflow='';document.getElementById('pixora-universe-home')?.removeAttribute('inert');returnFocus?.()}
function notify(text){panel.querySelector('.cs-toast').textContent=text;clearTimeout(timer);timer=setTimeout(()=>panel.querySelector('.cs-toast').textContent='',3500)}
async function copy(text){try{await navigator.clipboard.writeText(text);notify('色碼已複製。')}catch{notify('無法存取剪貼簿，請直接選取色碼複製。')}}
async function accept(file){
 if(!file)return;if(!/^image\/(png|jpeg|webp|avif)$/.test(file.type)){notify('請選擇 JPG、PNG、WEBP 或 AVIF。');return}if(file.size>20*1024*1024){notify('圖片請小於 20MB。');return}
 const current=++revision;panel.querySelector('.cs-status').textContent='正在讀取圖片…'
 try{const url=URL.createObjectURL(file),image=new Image();try{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url})}finally{URL.revokeObjectURL(url)}if(current!==revision)return;state.source=image;state.name=file.name;showImage();analyze()}catch{if(current!==revision)return;panel.querySelector('.cs-status').textContent=state.palette.length?'讀取失敗，保留上一份分析。':'圖片無法讀取，請換一張圖片。';notify('圖片無法讀取。')}
}
function demo(){revision++;const canvas=document.createElement('canvas');canvas.width=800;canvas.height=500;const ctx=canvas.getContext('2d');[['#E95D48',.4],['#1D3546',.3],['#F0E6D4',.2],['#D6A44D',.1]].reduce((x,[color,fraction])=>{ctx.fillStyle=color;ctx.fillRect(x,0,canvas.width*fraction,canvas.height);return x+canvas.width*fraction},0);state.source=canvas;state.name='範例色塊（40% / 30% / 20% / 10%）';showImage();analyze()}
function showImage(){const preview=panel.querySelector('.cs-image');const imageCanvas=document.createElement('canvas'),width=state.source.naturalWidth||state.source.width,height=state.source.naturalHeight||state.source.height,scale=Math.min(1,1400/Math.max(width,height));imageCanvas.width=Math.max(1,Math.round(width*scale));imageCanvas.height=Math.max(1,Math.round(height*scale));imageCanvas.getContext('2d').drawImage(state.source,0,0,imageCanvas.width,imageCanvas.height);preview.src=imageCanvas.toDataURL();preview.hidden=false;panel.querySelector('.cs-empty').hidden=true;panel.querySelector('.cs-source').textContent=state.name}
function analyze(){
 const canvas=document.createElement('canvas'),w=state.source.naturalWidth||state.source.width,h=state.source.naturalHeight||state.source.height,scale=Math.min(1,256/Math.max(w,h));canvas.width=Math.max(1,Math.round(w*scale));canvas.height=Math.max(1,Math.round(h*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.imageSmoothingEnabled=false;ctx.drawImage(state.source,0,0,canvas.width,canvas.height);const data=ctx.getImageData(0,0,canvas.width,canvas.height).data,bins=new Map();let total=0
 for(let i=0;i<data.length;i+=4){if(data[i+3]<128)continue;const key=(data[i]>>4)*256+(data[i+1]>>4)*16+(data[i+2]>>4);let bin=bins.get(key);if(!bin){bin={n:0,sum:[0,0,0]};bins.set(key,bin)}bin.n++;for(let c=0;c<3;c++)bin.sum[c]+=data[i+c];total++}
 if(!total){state.palette=[];state.edited=false;panel.querySelector('.cs-status').textContent='圖片沒有可分析的不透明像素。';render();return}
 const colors=[...bins.values()].map(b=>({n:b.n,rgb:b.sum.map(x=>x/b.n)}));let boxes=[colors]
 const range=box=>[0,1,2].map(c=>Math.max(...box.map(x=>x.rgb[c]))-Math.min(...box.map(x=>x.rgb[c])))
 while(boxes.length<state.count){let best=-1,score=-1;boxes.forEach((box,i)=>{if(box.length<2)return;const value=Math.max(...range(box))*Math.sqrt(box.reduce((n,x)=>n+x.n,0));if(value>score){score=value;best=i}});if(best<0)break;const box=boxes.splice(best,1)[0],ranges=range(box),channel=ranges.indexOf(Math.max(...ranges));box.sort((a,b)=>a.rgb[channel]-b.rgb[channel]);const half=box.reduce((n,x)=>n+x.n,0)/2;let sum=0,split=1;for(let i=0;i<box.length-1;i++){sum+=box[i].n;split=i+1;if(sum>=half)break}boxes.push(box.slice(0,split),box.slice(split))}
 const combined=new Map();boxes.forEach(box=>{const n=box.reduce((sum,x)=>sum+x.n,0),color=[0,1,2].map(c=>Math.round(box.reduce((sum,x)=>sum+x.rgb[c]*x.n,0)/n)),value=hex(color);if(combined.has(value))combined.get(value).pixels+=n;else combined.set(value,{hex:value,pixels:n})});state.palette=[...combined.values()].sort((a,b)=>b.pixels-a.pixels).map(x=>({...x,percent:x.pixels/total*100}));state.edited=false;panel.querySelector('.cs-status').textContent=`已擷取 ${state.palette.length} 色 · 主色 ${state.palette[0].hex} · 取樣 ${total.toLocaleString()} 像素`;render()
}
function render(){
 const box=panel.querySelector('.cs-palette');box.replaceChildren();panel.querySelectorAll('[data-export],.cs-copy-all').forEach(b=>b.disabled=!state.palette.length)
 state.palette.forEach((color,i)=>{const card=document.createElement('article'),values=rgb(color.hex),check=contrast(values);card.className='cs-swatch';card.innerHTML=`<div class="cs-color" style="background:${color.hex};color:${check.text}"><span>${String(i+1).padStart(2,'0')}</span><b>Aa</b><small>${color.percent.toFixed(1)}%</small></div><div class="cs-values"><button class="cs-hex" title="複製 HEX">${color.hex}</button><p>RGB ${values.join(' / ')}</p><p>建議${check.text==='#000000'?'黑':'白'}字 · 對比 ${check.ratio.toFixed(2)} : 1</p><label>調整色彩<input type="color" value="${color.hex}" aria-label="調整第 ${i+1} 色"></label></div>`;card.querySelector('.cs-hex').onclick=()=>copy(color.hex);card.querySelector('input').oninput=e=>{color.hex=e.target.value.toUpperCase();state.edited=true;panel.querySelector('.cs-status').textContent='已手動調色。比例保留原始像素分類估計值。';render()};box.append(card)})
}
function save(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
async function exportPalette(type){if(!state.palette.length)return;try{if(type==='png'){const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=900;const ctx=canvas.getContext('2d');ctx.fillStyle='#F5F0E7';ctx.fillRect(0,0,1600,900);ctx.fillStyle='#292722';ctx.font='bold 46px Arial';ctx.fillText('PIXORA / COLOR INDEX',60,85);const width=1480/state.palette.length;state.palette.forEach((color,i)=>{const x=60+i*width;ctx.fillStyle=color.hex;ctx.fillRect(x,150,width,500);ctx.fillStyle='#292722';ctx.font='bold '+Math.min(26,width*.15)+'px Arial';ctx.fillText(color.hex,x+10,704);ctx.font='22px Arial';ctx.fillText(color.percent.toFixed(1)+'%',x+10,744)});ctx.font='20px Arial';ctx.fillText('RGB / LOCAL ANALYSIS'+(state.edited?' / MANUALLY EDITED':''),60,840);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error();save(blob,'pixora-palette.png')}else{const content=type==='css'?':root {\n'+state.palette.map((color,i)=>`  --palette-${i+1}: ${color.hex};`).join('\n')+'\n}\n':JSON.stringify({source:state.name,space:'sRGB',manuallyEdited:state.edited,colors:state.palette.map(color=>({hex:color.hex,rgb:rgb(color.hex),estimatedPercent:Number(color.percent.toFixed(2))}))},null,2);save(new Blob([content],{type:type==='css'?'text/css':'application/json'}),'pixora-palette.'+type)}notify('色票已匯出。')}catch{notify('匯出失敗，請重試。')}}
