export function setupHandwriting(panel,getText){
 const section=document.createElement('section');section.className='fs-handwriting';section.innerHTML=`<h2>手寫風格參考 <small>AI</small></h2><p>上傳字跡或書法圖片，用它的筆觸風格製作新的繁體中文文字圖片。</p><label>參考圖片（JPG／PNG／WebP，10 MB 內）<input class="hw-file" type="file" accept="image/jpeg,image/png,image/webp"></label><img class="hw-reference" alt="手寫風格參考圖片" hidden><div class="hw-save-tools"><label>範例名稱<input class="hw-example-name" type="text" maxlength="40" placeholder="例如：毛筆行書、手寫便條"></label><button class="hw-save" type="button" disabled>儲存為範例</button></div><h3>我的參考範例</h3><p>最多 8 張，儲存在此瀏覽器。清除網站資料或換裝置後不會保留。</p><p class="hw-example-status" role="status" aria-live="polite"></p><div class="hw-examples"></div><label><input class="hw-consent" type="checkbox">我同意將參考圖片與輸入文字傳送至 OpenAI，生成會使用付費 API。</label><p class="hw-status" role="status" aria-live="polite">正在檢查服務…</p><a class="hw-login" href="/api/private-auth?action=start" hidden>登入已授權帳號</a><button class="hw-generate" type="button" disabled>參考風格生成（1 張）</button><p>使用左側的文字、橫／直向與透明背景設定。AI 可能出現錯字，請檢查結果。此功能產生圖片，不會建立字型檔。生成僅限已授權帳號。</p><div class="hw-results"></div>`;panel.querySelector('.fs-work').before(section)
 const status=section.querySelector('.hw-status'),button=section.querySelector('.hw-generate');let image='',ready=false,busy=false,sequence=0
 const save=section.querySelector('.hw-save'),exampleStatus=section.querySelector('.hw-example-status');let saving=false
 let retryUntil=0,retryTimer=0;const update=()=>{const wait=Math.max(0,Math.ceil((retryUntil-Date.now())/1000));button.disabled=!ready||!image||!section.querySelector('.hw-consent').checked||busy||wait>0;button.textContent=busy?'正在生成，請稍候…':wait>0?'等待 '+wait+' 秒後可重試':'參考風格生成（1 張）';save.disabled=!image||saving;if(!wait&&retryTimer){clearInterval(retryTimer);retryTimer=0}}
 const database=new Promise((resolve,reject)=>{const request=indexedDB.open('pixora-handwriting-examples',1);request.onupgradeneeded=()=>request.result.createObjectStore('examples',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('Storage blocked'))})
 async function storage(mode,action){const db=await database;return new Promise((resolve,reject)=>{const transaction=db.transaction('examples',mode),request=action(transaction.objectStore('examples'));transaction.oncomplete=()=>resolve(request.result);transaction.onerror=()=>reject(transaction.error);transaction.onabort=()=>reject(transaction.error)})}
 async function renderExamples(){const examples=await storage('readonly',store=>store.getAll()),box=section.querySelector('.hw-examples');box.replaceChildren();if(!examples.length){const empty=document.createElement('p');empty.textContent='尚未儲存範例。上傳圖片後按「儲存為範例」。';box.append(empty)}for(const example of examples.sort((a,b)=>b.created-a.created)){const card=document.createElement('article'),use=document.createElement('button'),thumbnail=document.createElement('img'),name=document.createElement('span'),remove=document.createElement('button');use.type='button';use.className='hw-example-use';use.setAttribute('aria-label','使用範例 '+example.name);thumbnail.src=example.image;thumbnail.alt='';name.textContent=example.name;use.append(thumbnail,name);use.onclick=()=>{sequence++;image=example.image;section.querySelector('.hw-reference').src=image;section.querySelector('.hw-reference').hidden=false;section.querySelector('.hw-example-name').value=example.name;section.querySelector('.hw-file').value='';status.textContent='已選用範例：'+example.name;update()};remove.type='button';remove.textContent='移除';remove.setAttribute('aria-label','移除範例 '+example.name);remove.onclick=async()=>{try{await storage('readwrite',store=>store.delete(example.id));await renderExamples();exampleStatus.textContent='範例已移除。'}catch{exampleStatus.textContent='無法移除，請重試。'}};card.append(use,remove);box.append(card)}}
 save.onclick=async()=>{if(!image||saving)return;saving=true;update();try{const examples=await storage('readonly',store=>store.getAll());if(examples.length>=8){exampleStatus.textContent='已儲存 8 張，請先移除不需要的範例。';return}const name=section.querySelector('.hw-example-name').value.trim()||'手寫範例 '+(examples.length+1);await storage('readwrite',store=>store.put({id:crypto.randomUUID(),name,image,created:Date.now()}));await renderExamples();exampleStatus.textContent='範例已儲存，下次可直接選用。'}catch{exampleStatus.textContent='儲存失敗，瀏覽器可能限制儲存空間。'}finally{saving=false;update()}}
 renderExamples().catch(()=>{exampleStatus.textContent='此瀏覽器暫時無法讀取範例儲存空間。'})
 fetch('/api/handwriting').then(r=>r.json()).then(data=>{ready=data.configured&&data.authorized;status.textContent=!data.configured?'AI 生成尚未啟用：管理員需在 Vercel 設定 OPENAI_API_KEY。':!data.authorized?'請登入已授權帳號後生成。':'AI 服務已設定。每次生成 1 張，通常需要稍候。';section.querySelector('.hw-login').hidden=Boolean(data.authorized);update()}).catch(()=>status.textContent='無法檢查 AI 服務，請重新開啟工作台。')
 section.querySelector('.hw-consent').onchange=update
 section.querySelector('.hw-file').onchange=async event=>{const file=event.target.files[0],request=++sequence;image='';section.querySelector('.hw-reference').hidden=true;update();if(!file)return;if(file.size>10*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type)){status.textContent='請選擇 10 MB 內的 JPG、PNG 或 WebP。';return}try{const bitmap=await createImageBitmap(file);if(request!==sequence){bitmap.close();return}const canvas=document.createElement('canvas'),scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();image=canvas.toDataURL('image/jpeg',.8);if(image.length>2800000)throw new Error();section.querySelector('.hw-reference').src=image;section.querySelector('.hw-reference').hidden=false;status.textContent=ready?'參考圖片已準備好。':'參考圖片已準備好；AI 服務需啟用及登入。';update()}catch{status.textContent='無法讀取圖片，請重新選擇。'}}
 button.onclick=async()=>{const settings=getText();if(!settings.text.trim()){status.textContent='請先在左側輸入文字。';return}busy=true;update();status.textContent='正在參考筆觸生成，請稍候…';try{const response=await fetch('/api/handwriting',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...settings,image,consent:true}),signal:AbortSignal.timeout(120000)}),data=await response.json();if(!response.ok){if(['GENERATION_BUSY','COOLDOWN'].includes(data.code)&&Number.isFinite(data.retryAfter)){retryUntil=Date.now()+Math.min(120,Math.max(1,data.retryAfter))*1000;if(!retryTimer)retryTimer=setInterval(update,1000)}throw new Error(data.error||'生成失敗')}if(!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(data.image))throw new Error('無法讀取結果');const card=document.createElement('article'),result=document.createElement('img'),link=document.createElement('a');result.src=data.image;result.alt='AI 手寫文字：'+settings.text;link.href=data.image;link.download='pixora-handwriting-'+Date.now()+'.png';link.textContent='下載手寫 PNG';card.append(result,link);const results=section.querySelector('.hw-results');results.prepend(card);while(results.children.length>4)results.lastElementChild.remove();status.textContent='生成完成，請核對中文字再下載。'}catch(error){status.textContent=error.name==='TimeoutError'?'生成逾時，請稍後重試。':error.message}finally{busy=false;update()}}
}
