export function setupHandwritingHistory(section){
 const root=document.createElement('section');root.className='hw-history';root.innerHTML='<section class="hw-generated-preview" hidden><h3>生成圖片預覽</h3><img class="hw-generated-image" alt="生成的手寫中文圖片"><p class="hw-generated-caption"></p><a class="hw-generated-download">下載 PNG</a><button class="hw-save-generated" type="button">儲存生成圖片</button></section><h3>生成紀錄</h3><p>成功生成後自動儲存，最多 20 張。紀錄保存在此瀏覽器，清除網站資料或換裝置後不會保留。</p><p class="hw-history-status" role="status" aria-live="polite"></p><div class="hw-history-list"></div>';section.append(root)
 let latest=null,saving=false;const status=root.querySelector('.hw-history-status'),save=root.querySelector('.hw-save-generated')
 const database=new Promise((resolve,reject)=>{const request=indexedDB.open('pixora-handwriting-generations',1);request.onupgradeneeded=()=>request.result.createObjectStore('images',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('Storage blocked'))})
 async function storage(mode,action){const db=await database;return new Promise((resolve,reject)=>{const transaction=db.transaction('images',mode),request=action(transaction.objectStore('images'));transaction.oncomplete=()=>resolve(request.result);transaction.onerror=()=>reject(transaction.error);transaction.onabort=()=>reject(transaction.error)})}
 function show(record,scroll=false){latest=record;const box=root.querySelector('.hw-generated-preview');box.hidden=false;root.querySelector('.hw-generated-image').src=record.image;root.querySelector('.hw-generated-image').alt='AI 手寫文字：'+record.text;root.querySelector('.hw-generated-caption').textContent=record.text+' · '+new Date(record.created).toLocaleString('zh-HK');const download=root.querySelector('.hw-generated-download');download.href=record.image;download.download='pixora-handwriting-'+record.id+'.png';save.disabled=Boolean(record.saved);save.textContent=record.saved?'已儲存至生成紀錄':'儲存生成圖片';if(scroll)box.scrollIntoView({block:'center',behavior:'smooth'})}
 async function render(){const records=await storage('readonly',store=>store.getAll()),box=root.querySelector('.hw-history-list');box.replaceChildren();if(!records.length){const p=document.createElement('p');p.textContent='尚未有生成紀錄。';box.append(p)}for(const record of records.sort((a,b)=>b.created-a.created)){const card=document.createElement('article'),view=document.createElement('button'),image=document.createElement('img'),label=document.createElement('span'),date=document.createElement('small'),download=document.createElement('a'),remove=document.createElement('button');view.type='button';view.className='hw-history-view';view.setAttribute('aria-label','預覽生成圖片 '+record.text);image.src=record.image;image.alt='';label.textContent=record.text;view.append(image,label);view.onclick=()=>show({...record,saved:true},true);date.textContent=new Date(record.created).toLocaleString('zh-HK');download.href=record.image;download.download='pixora-handwriting-'+record.id+'.png';download.textContent='下載 PNG';remove.type='button';remove.textContent='移除紀錄';remove.onclick=async()=>{try{await storage('readwrite',store=>store.delete(record.id));if(latest?.id===record.id)show({...latest,saved:false});await render();status.textContent='紀錄已移除。'}catch{status.textContent='無法移除紀錄，請重試。'}};card.append(view,date,download,remove);box.append(card)}}
 async function persist(){if(!latest||latest.saved||saving)return;saving=true;save.disabled=true;const record={...latest};delete record.saved;try{const records=await storage('readonly',store=>store.getAll());if(records.length>=20&&!records.some(r=>r.id===record.id))throw new Error('紀錄已達 20 張，請下載並移除不需要的紀錄後再儲存。');await storage('readwrite',store=>store.put(record));if(latest?.id===record.id)show({...record,saved:true});await render();status.textContent='圖片已儲存，下次可在生成紀錄預覽及下載。'}catch(error){status.textContent=error.message.startsWith('紀錄已達')?error.message:'圖片已生成，但儲存失敗。請立即下載 PNG，或按「儲存生成圖片」重試。'}finally{saving=false;save.disabled=Boolean(latest?.saved)}}
 save.onclick=persist;render().catch(()=>status.textContent='無法讀取生成紀錄；新圖片仍可即時預覽與下載。')
 return async(image,settings)=>{show({id:crypto.randomUUID(),image,text:settings.text,vertical:settings.vertical,transparent:settings.transparent,created:Date.now(),saved:false},true);await persist()}
}
