import JSZip from 'jszip'
import './layer-studio.css'
let panel,returnFocus,canvas,ctx,selected=null,mode='rect',drawing=null,points=[],busy=false,revision=0
let width=1200,height=800,layers=[],history=[],serial=0
const $=s=>panel.querySelector(s)
const make=(w=width,h=height)=>Object.assign(document.createElement('canvas'),{width:w,height:h})
const active=()=>layers.find(l=>l.id===selected)
const safe=n=>(n||'layer').replace(/[\\/:*?"<>|]/g,'-').slice(0,70)
function status(message){$('.ls-status').textContent=message}
function remember(){history.push({width,height,layers:layers.map(l=>({...l})),selected});if(history.length>15)history.shift()}
function layer(image,name){return{id:++serial,image,name,x:0,y:0,scale:1,opacity:1,visible:true}}
function world(l){const c=make(),cctx=c.getContext('2d');cctx.drawImage(l.image,l.x,l.y,l.image.width*l.scale,l.image.height*l.scale);return c}
function draw(){ctx.clearRect(0,0,width,height);for(const l of layers)if(l.visible){ctx.globalAlpha=l.opacity;ctx.drawImage(l.image,l.x,l.y,l.image.width*l.scale,l.image.height*l.scale)}ctx.globalAlpha=1;ctx.save();ctx.strokeStyle='#8648ff';ctx.lineWidth=2*width/Math.max(1,canvas.clientWidth);ctx.setLineDash([6*width/Math.max(1,canvas.clientWidth),4*width/Math.max(1,canvas.clientWidth)]);if(drawing?.start&&mode==='rect'){ctx.strokeRect(drawing.start.x,drawing.start.y,drawing.end.x-drawing.start.x,drawing.end.y-drawing.start.y)}if(points.length){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}ctx.restore()}
function render(){canvas.width=width;canvas.height=height;draw();$('.ls-size').textContent=`${width} × ${height} px · ${layers.length} 個圖層`;const list=$('.ls-list');list.replaceChildren();for(const l of [...layers].reverse()){const row=document.createElement('div');row.className='ls-layer'+(selected===l.id?' active':'');const toggle=document.createElement('button');toggle.textContent=l.visible?'◉':'○';toggle.setAttribute('aria-label',`${l.visible?'隱藏':'顯示'} ${l.name}`);toggle.onclick=()=>{remember();l.visible=!l.visible;render()};const pick=document.createElement('button');pick.textContent=l.name;pick.onclick=()=>{selected=l.id;points=[];render()};pick.setAttribute('aria-pressed',String(selected===l.id));row.append(toggle,pick);list.append(row)}const l=active();$('.ls-name').value=l?.name||'';$('.ls-x').value=l?.x||0;$('.ls-y').value=l?.y||0;$('.ls-scale').value=Math.round((l?.scale||1)*100);$('.ls-opacity').value=Math.round((l?.opacity??1)*100);panel.querySelectorAll('[data-needs-layer]').forEach(el=>el.disabled=!l||busy);$('.ls-undo').disabled=!history.length||busy;$('.ls-finish').disabled=points.length<3||busy;$('.ls-zip').disabled=!layers.length||busy;$('.ls-flat').disabled=!layers.length||busy;panel.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)))}
function close(){revision++;points=[];drawing=null;panel.hidden=true;document.body.style.overflow='';document.getElementById('pixora-universe-home')?.removeAttribute('inert');returnFocus?.()}
export function openLayerStudio(callback){returnFocus=callback;document.getElementById('pixora-universe-home')?.setAttribute('inert','');document.body.style.overflow='hidden';if(panel){panel.hidden=false;render();return}panel=document.createElement('section');panel.id='layer-studio';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','本機分層工作台');panel.innerHTML=`<header class="ls-header"><button class="ls-back">← 回到行星選單</button><div><b>PIXORA / 圖片分層</b><small>SATURN · LOCAL LAYER STUDIO</small></div><button class="ls-zip" disabled>下載圖層 ZIP</button></header><div class="ls-shell"><aside class="ls-sidebar"><small>01 / YOUR MATERIALS</small><h2>拆開素材，<br>重新組合。</h2><button class="ls-source">加入原圖</button><button class="ls-import">匯入透明圖層 / ZIP</button><button class="ls-demo">試用分層範例</button><input class="ls-source-file" type="file" accept="image/png,image/jpeg,image/webp" hidden><input class="ls-import-file" type="file" accept="image/png,.zip" multiple hidden><p>所有圖片在瀏覽器處理，不設使用次數限制。重新整理頁面會清除工作，請先下載。</p><small>02 / LAYERS · 上方為最上層</small><div class="ls-list"></div><label>圖層名稱<input class="ls-name" data-needs-layer maxlength="70"></label><div class="ls-fields"><label>X 位移<input class="ls-x" data-needs-layer type="number" step="1"></label><label>Y 位移<input class="ls-y" data-needs-layer type="number" step="1"></label></div><label>縮放 %<input class="ls-scale" data-needs-layer type="number" min="5" max="400" step="5" value="100"></label><label>透明度 %<input class="ls-opacity" data-needs-layer type="range" min="0" max="100" value="100"></label><div class="ls-fields"><button class="ls-up" data-needs-layer>上移一層</button><button class="ls-down" data-needs-layer>下移一層</button><button class="ls-duplicate" data-needs-layer>複製圖層</button><button class="ls-delete" data-needs-layer>刪除圖層</button></div><button class="ls-single" data-needs-layer>下載所選圖層 PNG</button></aside><main class="ls-main"><div class="ls-intro"><small>FROM ONE IMAGE TO MANY LAYERS</small><h1>分層，讓每個元素自由。</h1><p>選擇一個圖層，再圈選要拆出的區域。可匯入其他 AI 工具輸出的透明 PNG 或圖層 ZIP。</p></div><div class="ls-tools"><button data-mode="rect" aria-pressed="true">矩形圈選</button><button data-mode="poly" aria-pressed="false">多邊形圈選</button><button data-mode="move" aria-pressed="false">移動圖層</button><button class="ls-finish" disabled>完成圈選</button><button class="ls-cancel">取消圈選</button><button class="ls-undo" disabled>復原</button></div><p class="ls-instruction">拖曳矩形圈選，放開後拆成新圖層。多邊形模式逐點點擊，再按完成圈選。</p><div class="ls-stage"><canvas aria-label="分層畫布，使用圈選工具或位移欄位編輯" tabindex="0"></canvas></div><footer><span class="ls-size"></span><button class="ls-flat" disabled>下載合成 PNG</button></footer><p class="ls-status" role="status">加入原圖或試用範例開始。</p><p class="ls-note">手動圈選會保留區域內所有像素，並在原圖層留下透明空洞。這不是 AI 自動辨識，也不會補回被遮住的背景。長邊超過 2400 px 的原圖會縮小；最多 30 層，單檔上限 30MB。</p></main></div>`;document.body.append(panel);canvas=$('canvas');ctx=canvas.getContext('2d');bind();render();$('.ls-source').focus()}
function split(path){const l=active();if(!l||!l.visible)return status('請先選擇一個可見圖層。');if(layers.length>=30)return status('最多 30 個圖層。');const original=world(l),cut=make(),remain=make(),a=cut.getContext('2d'),b=remain.getContext('2d');a.drawImage(original,0,0);a.globalCompositeOperation='destination-in';a.fill(path);const pixels=a.getImageData(0,0,width,height).data;let count=0;for(let i=3;i<pixels.length;i+=4)if(pixels[i])count++;if(!count)return status('圈選區域沒有像素，請重新圈選。');b.drawImage(original,0,0);b.globalCompositeOperation='destination-out';b.fill(path);remember();l.image=remain;l.x=l.y=0;l.scale=1;const added=layer(cut,`${l.name} · 圈選 ${serial+1}`);added.opacity=l.opacity;layers.splice(layers.indexOf(l)+1,0,added);selected=added.id;points=[];render();status('已拆成新圖層。原圖層的圈選區域已變透明，可用「復原」還原。')}
function position(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*width/r.width,y:(e.clientY-r.top)*height/r.height}}
function bind(){ $('.ls-back').onclick=close;$('.ls-source').onclick=()=>$('.ls-source-file').click();$('.ls-import').onclick=()=>$('.ls-import-file').click();$('.ls-source-file').onchange=e=>{const f=e.target.files[0];if(f)loadSource(f);e.target.value=''};$('.ls-import-file').onchange=e=>{importFiles([...e.target.files]);e.target.value=''};$('.ls-demo').onclick=demo;panel.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;points=[];drawing=null;render()});$('.ls-finish').onclick=()=>{if(points.length<3)return;const p=new Path2D();points.forEach((point,i)=>i?p.lineTo(point.x,point.y):p.moveTo(point.x,point.y));p.closePath();split(p)};$('.ls-cancel').onclick=()=>{points=[];drawing=null;render()};$('.ls-undo').onclick=()=>{const old=history.pop();if(old){({width,height,layers,selected}=old);points=[];render();status('已復原。')}};
  for(const [css,key] of [['.ls-name','name'],['.ls-x','x'],['.ls-y','y'],['.ls-scale','scale'],['.ls-opacity','opacity']])$(css).onchange=e=>{const l=active();if(!l)return;remember();if(key==='name')l.name=e.target.value.trim()||'未命名圖層';else {const n=Number(e.target.value);if(!Number.isFinite(n))return;l[key]=key==='scale'?Math.max(.05,Math.min(4,n/100)):key==='opacity'?Math.max(0,Math.min(1,n/100)):Math.max(-2400,Math.min(2400,n))}render()};
  for(const [css,delta] of [['.ls-up',1],['.ls-down',-1]])$(css).onclick=()=>{const i=layers.indexOf(active()),j=i+delta;if(j<0||j>=layers.length)return;remember();[layers[i],layers[j]]=[layers[j],layers[i]];render()};$('.ls-delete').onclick=()=>{remember();layers=layers.filter(l=>l.id!==selected);selected=layers.at(-1)?.id??null;points=[];render()};$('.ls-duplicate').onclick=()=>{if(layers.length>=30)return status('最多 30 個圖層。');const l=active();remember();const added={...l,id:++serial,name:l.name+' · 複製'};layers.splice(layers.indexOf(l)+1,0,added);selected=added.id;render()};$('.ls-single').onclick=()=>exportSingle();$('.ls-flat').onclick=()=>exportFlat();$('.ls-zip').onclick=()=>exportZip();
  canvas.onpointerdown=e=>{if(busy||!active())return;e.preventDefault();const p=position(e);if(mode==='poly'){points.push(p);render();return}if(mode==='move'){remember();drawing={start:p,end:p,x:active().x,y:active().y}}else drawing={start:p,end:p};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drawing)return;drawing.end=position(e);if(mode==='move'){active().x=drawing.x+drawing.end.x-drawing.start.x;active().y=drawing.y+drawing.end.y-drawing.start.y}draw()};canvas.onpointerup=e=>{if(!drawing)return;const d=drawing;drawing=null;if(mode==='rect'){const p=new Path2D();p.rect(Math.min(d.start.x,d.end.x),Math.min(d.start.y,d.end.y),Math.abs(d.end.x-d.start.x),Math.abs(d.end.y-d.start.y));split(p)}else render()};canvas.onpointercancel=()=>{drawing=null;render()};panel.addEventListener('keydown',e=>{if(e.key==='Escape'){if(points.length||drawing){points=[];drawing=null;render()}else close()}});$('.ls-stage').ondragover=e=>e.preventDefault();$('.ls-stage').ondrop=e=>{e.preventDefault();const files=[...e.dataTransfer.files];if(!layers.length&&files.length===1&&!files[0].name.endsWith('.zip'))loadSource(files[0]);else importFiles(files)};panel.addEventListener('paste',e=>{const files=[...e.clipboardData.files].filter(f=>f.type.startsWith('image/'));if(files.length){e.preventDefault();if(layers.length)importFiles(files);else loadSource(files[0])}})}
async function decode(file){if(file.size>30*1024*1024)throw Error('檔案需小於 30MB。');const url=URL.createObjectURL(file),image=new Image();try{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('圖片無法讀取。'));image.src=url});if(image.width*image.height>25000000)throw Error('圖片像素過大，請先縮小。');return image}finally{URL.revokeObjectURL(url)}}
async function loadSource(file){if(busy)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type))return status('請選擇 JPG、PNG 或 WEBP。');busy=true;const current=++revision;render();try{const image=await decode(file);if(current!==revision)return;remember();const ratio=Math.min(1,2400/Math.max(image.width,image.height));width=Math.max(1,Math.round(image.width*ratio));height=Math.max(1,Math.round(image.height*ratio));const c=make();c.getContext('2d').drawImage(image,0,0,width,height);layers=[layer(c,file.name)];selected=layers[0].id;points=[];status(ratio<1?'原圖已縮小至長邊 2400 px。加入原圖會建立新畫布；可用復原返回。':'原圖已加入。選擇圈選工具拆出素材。')}catch(e){status(e.message)}finally{busy=false;render()}}
async function importFiles(files){if(busy||!files.length)return;busy=true;const current=++revision;render();try{let items=[],manifest=null;for(const file of files){if(file.name.toLowerCase().endsWith('.zip')){if(file.size>30*1024*1024)throw Error('ZIP 需小於 30MB。');const zip=await JSZip.loadAsync(file);const entries=Object.values(zip.files).filter(f=>!f.dir&&/\.png$/i.test(f.name));if(entries.length>30)throw Error('ZIP 最多包含 30 張 PNG。');let total=0;for(const entry of entries){const blob=await entry.async('blob');total+=blob.size;if(total>60*1024*1024)throw Error('解壓後的素材過大。');items.push({file:new File([blob],entry.name,{type:'image/png'}),name:entry.name})}if(zip.file('layers.json')){const raw=await zip.file('layers.json').async('string');if(raw.length>100000)throw Error('圖層資料過大。');manifest=JSON.parse(raw)}}else{if(file.type!=='image/png')throw Error('匯入圖層請使用 PNG 或 ZIP。');items.push({file,name:file.name})}}if(!items.length)throw Error('沒有找到 PNG 圖層。');if(layers.length+items.length>30)throw Error('合計最多 30 個圖層。');const decoded=[];for(const item of items)decoded.push({...item,image:await decode(item.file)});if(current!==revision)return;remember();if(!layers.length){width=Math.min(2400,manifest?.width||decoded[0].image.width);height=Math.min(2400,manifest?.height||decoded[0].image.height);if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1)throw Error('畫布尺寸無效。')}for(const item of decoded){const c=make();c.getContext('2d').drawImage(item.image,0,0,width,height);const metadata=manifest?.layers?.find(l=>l.file===item.name);const l=layer(c,String(metadata?.name||item.name).slice(0,70));if(metadata){l.visible=metadata.visible!==false;l.opacity=Math.max(0,Math.min(1,Number(metadata.opacity)||0))}layers.push(l);selected=l.id}points=[];status('已匯入圖層。每張 PNG 對齊畫布；同一 AI 分層結果應使用相同尺寸。')}catch(e){status(e.message)}finally{busy=false;render()}}
function demo(){if(busy)return;revision++;remember();width=1200;height=800;const background=make(),b=background.getContext('2d');b.fillStyle='#EEEAF8';b.fillRect(0,0,width,height);const circle=make(),c=circle.getContext('2d');c.fillStyle='#F7B65E';c.beginPath();c.arc(430,400,200,0,Math.PI*2);c.fill();const text=make(),t=text.getContext('2d');t.fillStyle='#43345F';t.font='bold 105px sans-serif';t.fillText('MAKE',660,370);t.fillText('SPACE.',660,490);layers=[layer(background,'背景'),layer(circle,'圓形素材'),layer(text,'文字素材')];selected=layers[1].id;points=[];render();status('這是預先建立的三層示範，不是 AI 分層結果。試試移動、隱藏或圈選圖層。')}
const blob=c=>new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('圖片匯出失敗。')),'image/png'))
function download(b,name){const url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function exportSingle(){const l=active();if(!l)return;try{const c=world(l);const out=make();const context=out.getContext('2d');context.globalAlpha=l.opacity;context.drawImage(c,0,0);download(await blob(out),safe(l.name)+'.png');status('所選圖層已下載，PNG 保留畫布尺寸與透明背景。')}catch(e){status(e.message)}}
async function exportFlat(){try{const c=make(),context=c.getContext('2d');for(const l of layers)if(l.visible){context.globalAlpha=l.opacity;context.drawImage(l.image,l.x,l.y,l.image.width*l.scale,l.image.height*l.scale)}download(await blob(c),'pixora-composite.png');status('已下載可見圖層的合成圖片。')}catch(e){status(e.message)}}
async function exportZip(){if(busy)return;busy=true;render();try{const zip=new JSZip(),metadata=[];for(const [i,l] of layers.entries()){const file=`${String(i+1).padStart(2,'0')}-${safe(l.name)}.png`;zip.file(file,await blob(world(l)));metadata.push({file,name:l.name,visible:l.visible,opacity:l.opacity})}zip.file('layers.json',JSON.stringify({version:1,width,height,layers:metadata},null,2));zip.file('README.txt','PNG files use the full canvas size. Layer order is bottom to top. Positions and scale are baked into PNG pixels; opacity and visibility are stored in layers.json. Import the ZIP into Pixora to restore the composition.');download(await zip.generateAsync({type:'blob'}),'pixora-layers.zip');status('ZIP 已下載，包含透明 PNG 與圖層順序；可重新匯入 Pixora。')}catch(e){status(e.message)}finally{busy=false;render()}}
